rebaseMergeAllowed: true
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
- pattern: master
  isAdminEnforced: true
  requiredStatusCheckContexts:
    - 'test (10)'
    - 'test (12)'
    - 'test (14)'
    - 'windows'
    - 'lint'
    - 'docs'
    - 'ci / Summary Check for ci/kokoro: Samples test'
    - 'ci / Summary Check for ci/kokoro: System test'
    - 'cla/google'
  requiredApprovingReviewCount: 1
  requiresCodeOwnerReviews: true
  requiresStrictStatusChecks: true
permissionRules:
  - team: yoshi
    permission: pull
  - team: yoshi-nodejs
    permission: push
  - team: yoshi-admins
    permission: admin

